### ISSUE TITLE
BUG反馈，通过插入数据库方式或者调用接口/user/insertOne注册的用户均无法登入

### ISSUE THREAD

**Issue by lingshengjiang** [lishanghan/easyAutoTesting#2]
![image](https://user-images.githubusercontent.com/48236287/60791036-6482bf00-a195-11e9-9630-3681d7680ab4.png)
![image](https://user-images.githubusercontent.com/48236287/60791064-74020800-a195-11e9-8478-6353adc6ce92.png)
<img width="722" alt="image" src="https://user-images.githubusercontent.com/48236287/60791196-b1ff2c00-a195-11e9-91a1-fbb35964fdc2.png">

**Comment by lingshengjiang** [comment]
![image](https://user-images.githubusercontent.com/48236287/60791590-8d578400-a196-11e9-80a3-c91ef7092a26.png)
直接调用登入接口也直接返回密码错误

**Comment by lishanghan** [comment]
这里有本公司的一些特殊需求不便修改，你可以insert的时候 groupid 填11，代表测试组；或者修改user的insertOne和login接口源码代码去掉邮箱后缀的判断

**Comment by lishanghan** [comment]
修改了建库sql，执行项目根目录下hry_auto.sql进行建库，默认登陆名：admin，密码：123456
