### ISSUE TITLE
为啥新建接口之后需要额外调用接口来生成测试类，这个设计不太明白

### ISSUE THREAD

**Issue by lingshengjiang** [lishanghan/easyAutoTesting#3]
生成默认服务测试类：新建好服务、服务环境映射，接口候后，调用
        http://localhost:8885/autocode/generateTestClass?debug=true 接口
        生成的文件存在本地C盘，将生成的测试类拷贝到项目src/main/java/hry/testng/test/路径下，重新打包部署 

问题：
1、是不是每次新建完接口都要去手动拷贝测试类然后重新打包
2、线上部署是不是在jar包外部建立文件夹然后调用generateTestClass生成测试类拷贝到对应文件夹就行

**Comment by lingshengjiang** [comment]
![image](https://user-images.githubusercontent.com/48236287/61021122-bb290c80-a3d2-11e9-927c-0a0752d362a4.png)
我的测试-服务接口-用例-请选择测试类下拉框没法选择。已经调用接口生成测试类并且重新编译

**Comment by lishanghan** [comment]
1、可以把某个服务下所有接口录入完后，统一生成测试类
2、由于之前时间紧张想出这个折中的方案，后续可能会优化，或者你有更好的解决方案可以修改源代码
解决方向要么自己写一套执行用例的方法框架，不使用testng的框架；要么解决新生成的测试类文件或新增接口修改后的文件怎么重新编译后更新已部署服务的jar包
